allowBuilds:
  "@google/genai": true
  '@tree-sitter-grammars/tree-sitter-kotlin': false
  better-sqlite3: true
  protobufjs: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
